server.address=127.0.0.1
server.port=18081
spring.application.name=git-runner
developer-dungeon.runner.token=${DEVELOPER_DUNGEON_RUNNER_TOKEN:}
developer-dungeon.runner.image-id=${DEVELOPER_DUNGEON_CHALLENGE_IMAGE_ID:}
developer-dungeon.runner.image-fingerprint=${DEVELOPER_DUNGEON_CHALLENGE_IMAGE_FINGERPRINT:}
developer-dungeon.runner.docker-executable=${DEVELOPER_DUNGEON_DOCKER_EXECUTABLE:docker}
