package jp.yuya.dev.developerdungeon.contract;

public enum CommandKind {
    STATUS, LOG_ONELINE, LOG_ONELINE_ALL_DECORATE, BRANCH, SHOW, SWITCH, CHERRY_PICK, RESET_HARD, REVERT_NO_EDIT,
    DIFF, DIFF_STAGED, STASH_PUSH, STASH_LIST, STASH_POP
}
