package jp.yuya.dev.developerdungeon.contract;

public enum CommandKind {
    STATUS, LOG_ONELINE, LOG_ONELINE_ALL_DECORATE, BRANCH, SHOW, SWITCH, CHERRY_PICK, RESET_HARD,
    REVERT_NO_EDIT, REVERT_NO_COMMIT, COMMIT_RESTORE_SETTINGS,
    DIFF, DIFF_STAGED, STASH_PUSH, STASH_LIST, STASH_POP, STASH_APPLY, STASH_DROP,
    LOG_GRAPH_ALL, MERGE_PROFILE_MESSAGE, ADD_PROFILE_MESSAGES, COMMIT_NO_EDIT, COMMIT_ALL_NO_EDIT,
    REFLOG_HEAD, CREATE_PAYMENT_RETRY_BRANCH, SWITCH_PAYMENT_RETRY, SWITCH_CREATE_PAYMENT_RETRY,
    ADD_TRAINING_INTRO, COMMIT_TRAINING_ONE, UNSTAGE_TRAINING_REPORT, ADD_TRAINING_IGNORE,
    ADD_TRAINING_CONFIG, COMMIT_TRAINING_TWO, SWITCH_CREATE_TRAINING_BRANCH,
    SWITCH_TRAINING_BRANCH, ADD_TRAINING_HANDOFF, COMMIT_TRAINING_THREE
}
