package jp.yuya.dev.developerdungeon.contract;

public enum CommandKind {
    STATUS, LOG_ONELINE, LOG_ONELINE_ALL_DECORATE, BRANCH, SHOW, SWITCH, CHERRY_PICK, RESET_HARD, REVERT_NO_EDIT,
    DIFF, DIFF_STAGED, STASH_PUSH, STASH_LIST, STASH_POP,
    LOG_GRAPH_ALL, MERGE_PROFILE_MESSAGE, ADD_PROFILE_MESSAGES, COMMIT_NO_EDIT,
    REFLOG_HEAD, CREATE_PAYMENT_RETRY_BRANCH, SWITCH_PAYMENT_RETRY
}
